from __future__ import annotations

import argparse
import json
import sys

import requests

from crypto_utils import public_key_from_private_key, sign_vote


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Submit a vote to a blockchain voting node.",
    )
    parser.add_argument("voter_id", help="Unique voter identifier")
    parser.add_argument("candidate_id", help="Candidate identifier")
    parser.add_argument("election_id", help="Election identifier")
    parser.add_argument(
        "--node",
        default="http://127.0.0.1:8001",
        help="Base URL of the node (default: http://127.0.0.1:8001)",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=10,
        help="Request timeout in seconds (default: 10)",
    )
    parser.add_argument(
        "--private-key",
        help="Base64 Ed25519 private key used to sign the vote",
    )
    parser.add_argument(
        "--wallet-file",
        help="Path to wallet JSON generated by generate_wallet.py",
    )
    return parser.parse_args()


def resolve_private_key(args: argparse.Namespace) -> str:
    if args.private_key:
        return args.private_key.strip()

    if args.wallet_file:
        try:
            with open(args.wallet_file, "r", encoding="utf-8") as handle:
                wallet = json.load(handle)
        except OSError as error:
            raise ValueError(f"Failed to read wallet file: {error}") from error
        except json.JSONDecodeError as error:
            raise ValueError("Wallet file is not valid JSON") from error

        private_key = str(wallet.get("private_key", "")).strip()
        if not private_key:
            raise ValueError("Wallet file does not contain private_key")
        return private_key

    raise ValueError("Provide --private-key or --wallet-file")


def main() -> int:
    args = parse_args()
    node = args.node.rstrip("/")

    try:
        private_key = resolve_private_key(args)
        public_key = public_key_from_private_key(private_key)
        signature = sign_vote(
            args.voter_id,
            args.candidate_id,
            args.election_id,
            private_key,
        )
    except ValueError as error:
        print(str(error), file=sys.stderr)
        return 1

    payload = {
        "voter_id": args.voter_id,
        "candidate_id": args.candidate_id,
        "election_id": args.election_id,
        "voter_public_key": public_key,
        "signature": signature,
    }

    try:
        response = requests.post(
            f"{node}/votes",
            json=payload,
            timeout=args.timeout,
        )
    except requests.RequestException as error:
        print(f"Request failed: {error}", file=sys.stderr)
        return 1

    if response.ok:
        data = response.json()
        print(data.get("message", "Vote submitted"))
        print(f"pending_votes={data.get('pending_votes', 'unknown')}")
        return 0

    print(f"Node returned {response.status_code}: {response.text}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())