services:
  node1:
    build: .
    container_name: blockchain-node1
    environment:
      DIFFICULTY: "3"
      BLOCKCHAIN_DATA: "/data/node1.json"
      PORT: "8001"
      CORS_ALLOW_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173,http://127.0.0.1:4173"
      SELF_NODE_URL: "http://node1:8001"
      PEER_NODES: "http://node2:8002,http://node3:8003"
    ports:
      - "8001:8001"
    volumes:
      - ./data/node1.json:/data/node1.json

  node2:
    build: .
    container_name: blockchain-node2
    environment:
      DIFFICULTY: "3"
      BLOCKCHAIN_DATA: "/data/node2.json"
      PORT: "8002"
      CORS_ALLOW_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173,http://127.0.0.1:4173"
      SELF_NODE_URL: "http://node2:8002"
      PEER_NODES: "http://node1:8001,http://node3:8003"
    ports:
      - "8002:8002"
    volumes:
      - ./data/node2.json:/data/node2.json

  node3:
    build: .
    container_name: blockchain-node3
    environment:
      DIFFICULTY: "3"
      BLOCKCHAIN_DATA: "/data/node3.json"
      PORT: "8003"
      CORS_ALLOW_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173,http://127.0.0.1:4173"
      SELF_NODE_URL: "http://node3:8003"
      PEER_NODES: "http://node1:8001,http://node2:8002"
    ports:
      - "8003:8003"
    volumes:
      - ./data/node3.json:/data/node3.json
