from __future__ import annotations

import argparse
import json
import sys

import requests


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Register a voter public key on a blockchain voting node.",
    )
    parser.add_argument("voter_id", help="Unique voter identifier")
    parser.add_argument(
        "--public-key",
        help="Base64 Ed25519 public key to register",
    )
    parser.add_argument(
        "--wallet-file",
        help="Path to wallet JSON generated by generate_wallet.py",
    )
    parser.add_argument(
        "--node",
        default="http://127.0.0.1:8001",
        help="Base URL of the node (default: http://127.0.0.1:8001)",
    )
    parser.add_argument(
        "--admin-token",
        default="",
        help="Admin token if node is configured with ADMIN_TOKEN",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=10,
        help="Request timeout in seconds (default: 10)",
    )
    return parser.parse_args()


def resolve_public_key(args: argparse.Namespace) -> str:
    if args.public_key:
        return args.public_key.strip()

    if args.wallet_file:
        try:
            with open(args.wallet_file, "r", encoding="utf-8") as handle:
                wallet = json.load(handle)
        except OSError as error:
            raise ValueError(f"Failed to read wallet file: {error}") from error
        except json.JSONDecodeError as error:
            raise ValueError("Wallet file is not valid JSON") from error

        public_key = str(wallet.get("public_key", "")).strip()
        if not public_key:
            raise ValueError("Wallet file does not contain public_key")
        return public_key

    raise ValueError("Provide --public-key or --wallet-file")


def main() -> int:
    args = parse_args()
    node = args.node.rstrip("/")

    try:
        public_key = resolve_public_key(args)
    except ValueError as error:
        print(str(error), file=sys.stderr)
        return 1

    headers: dict[str, str] = {}
    if args.admin_token.strip():
        headers["X-Admin-Token"] = args.admin_token.strip()

    payload = {
        "voter_id": args.voter_id,
        "voter_public_key": public_key,
    }

    try:
        response = requests.post(
            f"{node}/voters/register",
            json=payload,
            headers=headers,
            timeout=args.timeout,
        )
    except requests.RequestException as error:
        print(f"Request failed: {error}", file=sys.stderr)
        return 1

    if response.ok:
        data = response.json()
        print(data.get("message", "Voter registered"))
        print(f"voter_id={data.get('voter_id', args.voter_id)}")
        print(f"registered_voters={data.get('registered_voters', 'unknown')}")
        return 0

    print(f"Node returned {response.status_code}: {response.text}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
